"""Shared test fixtures - async client, in-memory DB, mocked MarkerService."""

from __future__ import annotations

import os
import pathlib
import asyncio
import shutil
from typing import Any, AsyncGenerator

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

# Must be set before importing app modules
os.environ["ENCRYPTION_KEY"] = "dGVzdC1lbmNyeXB0aW9uLWtleS1mb3ItdW5pdHRlc3Q="

from app.database import Base, get_db
from app.kernel.models import (  # noqa: F401 - ensure kernel tables are registered
    KernelCommitHead,
    KernelCommitManifest,
    KernelOutbox,
    KernelPayloadObject,
    KernelRecord,
    KernelRecordEdge,
    KernelViewHead,
)
from app.models.audit import AuditEvent  # noqa: F401 - ensure table is registered
from app.models.job import ConversionJob  # noqa: F401 - ensure table is registered
from app.models.job_event import JobEvent  # noqa: F401 - ensure table is registered
from app.models.settings import Setting  # noqa: F401


# ---------------------------------------------------------------------------
# In-memory SQLite engine & session factory
# ---------------------------------------------------------------------------

TEST_DATABASE_URL = "sqlite+aiosqlite:///:memory:"

test_engine = create_async_engine(
    TEST_DATABASE_URL,
    echo=False,
    future=True,
    connect_args={"check_same_thread": False},
)
test_session_factory = async_sessionmaker(
    test_engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def _override_get_db() -> AsyncGenerator[AsyncSession, None]:
    """Drop-in replacement for get_db that uses the test engine."""
    async with test_session_factory() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# ---------------------------------------------------------------------------
# Office fixture generation (gitignored, rebuilt per session on first run)
# ---------------------------------------------------------------------------

_OFFICE_FIXTURE_NAMES = (
    "simple_headings.docx",
    "tables_links_lists.docx",
    "embedded_text_screenshot.docx",
    "title_text_notes.pptx",
    "table_chart_images.pptx",
)


def _build_office_fixtures() -> None:
    """Build complete office fixture set once, before xdist workers start."""
    fixture_dir = pathlib.Path(__file__).parent / "fixtures" / "conversion"
    if all((fixture_dir / name).exists() for name in _OFFICE_FIXTURE_NAMES):
        return
    fixture_dir.mkdir(parents=True, exist_ok=True)
    from tests.office_fixtures import (
        generate_docx_fixtures,
        generate_pptx_fixtures,
    )

    generate_docx_fixtures(fixture_dir)
    generate_pptx_fixtures(fixture_dir)


def pytest_configure(config: pytest.Config) -> None:
    """Controller creates shared generated fixtures before worker processes."""
    if not hasattr(config, "workerinput"):
        _build_office_fixtures()


@pytest.fixture(scope="session", autouse=True)
def _ensure_office_fixtures() -> None:
    """Build synthetic DOCX/PPTX fixtures if absent so tests run on a fresh clone.

    Fixtures live under tests/fixtures/conversion (gitignored to keep the repo
    small). Generated by _generate.py via python-docx / python-pptx,
    deterministically, so a clean checkout produces the same bytes.
    """
    _build_office_fixtures()


# ---------------------------------------------------------------------------
# Fake MarkerService
# ---------------------------------------------------------------------------

class FakeMarkerService:
    """Replaces MarkerService so tests never load real ML models."""

    def __init__(self) -> None:
        self._initialized = False

    def initialize(self) -> None:
        self._initialized = True

    def convert_file(self, filepath: str, options: dict[str, Any], device: str | None = None) -> dict[str, Any]:
        """Return a deterministic fake conversion result."""
        return {
            "text": "# Fake Markdown\n\nConverted successfully.",
            "extension": "md",
            "images": [],
            "metadata": {"pages": 1},
        }


class FakeTaskManager:
    """Minimal TaskManager that runs conversion synchronously in-process."""

    def __init__(self) -> None:
        self._progress: dict[str, int] = {}
        self._status: dict[str, str] = {}
        self._marker_service: FakeMarkerService | None = None

    def set_marker_service(self, svc: FakeMarkerService) -> None:
        self._marker_service = svc

    def submit_job(
        self,
        job_id: str,
        filepath: str,
        config: dict[str, Any],
        conversion_service: Any,
    ) -> None:
        """Immediately run the fake conversion so tests don't need threads."""
        self._progress[job_id] = 0
        self._status[job_id] = "processing"
        # Simulate completion instantly
        self._progress[job_id] = 100
        self._status[job_id] = "completed"

    def get_status(self, job_id: str) -> dict[str, Any]:
        return {
            "job_id": job_id,
            "status": self._status.get(job_id, "pending"),
            "progress": self._progress.get(job_id, 0),
        }

    async def cancel_job(self, job_id: str) -> bool:
        self._status[job_id] = "cancelled"
        self._progress.pop(job_id, None)
        return True

    async def job_events(self, request, job_id: str):
        """Yield one progress + one terminal event, then stop."""
        from sse_starlette.event import ServerSentEvent
        import json

        info = self.get_status(job_id)
        # Yield a progress event
        yield ServerSentEvent(
            data=json.dumps({"job_id": job_id, "status": "processing", "progress": 50}),
            event="progress",
        )
        # Yield a terminal status event
        yield ServerSentEvent(
            data=json.dumps(info),
            event="status",
        )


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def event_loop():
    """Create a single event loop for the entire test session."""
    loop = asyncio.new_event_loop()
    yield loop
    loop.close()


@pytest.fixture(autouse=True)
def ensure_current_event_loop(event_loop):
    """Keep the session event loop current for every test.

    pytest-asyncio 0.24 executes async TESTS on the *current* event
    loop while async FIXTURES run on the session-scoped ``event_loop``
    fixture. Anything that calls ``asyncio.run`` in the main thread
    (Alembic's sync migration entry does — see ``alembic/env.py``)
    leaves the current loop unset when it finishes. Repairing that by
    minting a *new* loop splits fixtures and tests onto different
    loops: coordinators and background tasks created by fixtures sit
    parked on the session loop while the test body runs elsewhere, and
    suite-order-dependent stalls follow (the source-ingress timeouts).
    The only correct repair is to rebind the session loop as current.
    """
    asyncio.set_event_loop(event_loop)
    yield


@pytest_asyncio.fixture(autouse=True)
async def setup_db():
    """Create tables before each test and drop them after."""
    async with test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield
    async with test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)


@pytest_asyncio.fixture
async def client() -> AsyncGenerator[AsyncClient, None]:
    """Provide an httpx AsyncClient wired to the FastAPI app with overrides."""
    from app.main import app, _app_state
    from app.services.conversion_service import ConversionService

    fake_service = FakeMarkerService()
    fake_conversion = ConversionService(fake_service)
    fake_tm = FakeTaskManager()
    fake_tm.set_marker_service(fake_service)

    original_ms = _app_state.marker_service
    original_cs = _app_state.conversion_service
    original_tm = _app_state.task_manager

    _app_state.marker_service = fake_service  # type: ignore[assignment]
    _app_state.conversion_service = fake_conversion  # type: ignore[assignment]
    _app_state.task_manager = fake_tm  # type: ignore[assignment]

    app.dependency_overrides[get_db] = _override_get_db

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://testserver") as ac:
        yield ac

    # Restore
    _app_state.marker_service = original_ms  # type: ignore[assignment]
    _app_state.conversion_service = original_cs  # type: ignore[assignment]
    _app_state.task_manager = original_tm  # type: ignore[assignment]
    app.dependency_overrides.clear()


@pytest_asyncio.fixture
async def db_session() -> AsyncGenerator[AsyncSession, None]:
    """Provide a raw async DB session for direct DB assertions."""
    async with test_session_factory() as session:
        yield session


@pytest_asyncio.fixture(scope="session")
async def _kernel_migration_template(tmp_path_factory: pytest.TempPathFactory) -> pathlib.Path:
    """Migrate one pristine SQLite database for isolated per-test copies."""
    from app.db_migration import upgrade_database

    template = tmp_path_factory.mktemp("kernel-migration-template") / "kernel.db"
    url = f"sqlite+aiosqlite:///{template.as_posix()}"
    await upgrade_database(url=url)
    return template


@pytest_asyncio.fixture
async def kernel_env(
    tmp_path: pathlib.Path,
    _kernel_migration_template: pathlib.Path,
) -> AsyncGenerator[async_sessionmaker, None]:
    """File-backed SQLite DB copied from the migrated per-worker template."""
    db_path = tmp_path / "kernel.db"
    shutil.copyfile(_kernel_migration_template, db_path)
    url = f"sqlite+aiosqlite:///{db_path.as_posix()}"
    engine = create_async_engine(url, connect_args={"check_same_thread": False})
    factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    try:
        yield factory
    finally:
        await engine.dispose()


@pytest_asyncio.fixture
async def payload_env(
    tmp_path: pathlib.Path,
    _kernel_migration_template: pathlib.Path,
) -> AsyncGenerator[tuple, None]:
    """Kernel DB copy plus isolated content-addressed payload store."""
    from app.kernel.commit import KernelCommitService
    from app.kernel.payloads import LocalPayloadStore

    db_path = tmp_path / "kernel.db"
    shutil.copyfile(_kernel_migration_template, db_path)
    url = f"sqlite+aiosqlite:///{db_path.as_posix()}"
    engine = create_async_engine(url, connect_args={"check_same_thread": False})
    factory = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    store = LocalPayloadStore(tmp_path / "payloads")
    service = KernelCommitService(factory, payload_store=store)
    try:
        yield factory, store, service
    finally:
        await engine.dispose()
