"""Shared test fixtures - async client, in-memory DB, mocked MarkerService."""

from __future__ import annotations

import os
import pathlib
import asyncio
from typing import Any, AsyncGenerator

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

# Must be set before importing app modules
os.environ["ENCRYPTION_KEY"] = "dGVzdC1lbmNyeXB0aW9uLWtleS1mb3ItdW5pdHRlc3Q="

from app.database import Base, get_db
from app.models.audit import AuditEvent  # noqa: F401 - ensure table is registered
from app.models.job import ConversionJob  # noqa: F401 - ensure table is registered
from app.models.job_event import JobEvent  # noqa: F401 - ensure table is registered
from app.models.settings import Setting  # noqa: F401


# ---------------------------------------------------------------------------
# In-memory SQLite engine & session factory
# ---------------------------------------------------------------------------

TEST_DATABASE_URL = "sqlite+aiosqlite:///:memory:"

test_engine = create_async_engine(
    TEST_DATABASE_URL,
    echo=False,
    future=True,
    connect_args={"check_same_thread": False},
)
test_session_factory = async_sessionmaker(
    test_engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def _override_get_db() -> AsyncGenerator[AsyncSession, None]:
    """Drop-in replacement for get_db that uses the test engine."""
    async with test_session_factory() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# ---------------------------------------------------------------------------
# Office fixture generation (gitignored, rebuilt per session on first run)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session", autouse=True)
def _ensure_office_fixtures() -> None:
    """Build synthetic DOCX/PPTX fixtures if absent so tests run on a fresh clone.

    Fixtures live under tests/fixtures/conversion (gitignored to keep the repo
    small). Generated by _generate.py via python-docx / python-pptx,
    deterministically, so a clean checkout produces the same bytes.
    """
    fixture_dir = pathlib.Path(__file__).parent / "fixtures" / "conversion"
    if (fixture_dir / "table_chart_images.pptx").exists():
        return
    fixture_dir.mkdir(parents=True, exist_ok=True)
    from tests.office_fixtures import (
        generate_docx_fixtures,
        generate_pptx_fixtures,
    )
    generate_docx_fixtures(fixture_dir)
    generate_pptx_fixtures(fixture_dir)


# ---------------------------------------------------------------------------
# Fake MarkerService
# ---------------------------------------------------------------------------

class FakeMarkerService:
    """Replaces MarkerService so tests never load real ML models."""

    def __init__(self) -> None:
        self._initialized = False

    def initialize(self) -> None:
        self._initialized = True

    def convert_file(self, filepath: str, options: dict[str, Any], device: str | None = None) -> dict[str, Any]:
        """Return a deterministic fake conversion result."""
        return {
            "text": "# Fake Markdown\n\nConverted successfully.",
            "extension": "md",
            "images": [],
            "metadata": {"pages": 1},
        }


class FakeTaskManager:
    """Minimal TaskManager that runs conversion synchronously in-process."""

    def __init__(self) -> None:
        self._progress: dict[str, int] = {}
        self._status: dict[str, str] = {}
        self._marker_service: FakeMarkerService | None = None

    def set_marker_service(self, svc: FakeMarkerService) -> None:
        self._marker_service = svc

    def submit_job(
        self,
        job_id: str,
        filepath: str,
        config: dict[str, Any],
        conversion_service: Any,
    ) -> None:
        """Immediately run the fake conversion so tests don't need threads."""
        self._progress[job_id] = 0
        self._status[job_id] = "processing"
        # Simulate completion instantly
        self._progress[job_id] = 100
        self._status[job_id] = "completed"

    def get_status(self, job_id: str) -> dict[str, Any]:
        return {
            "job_id": job_id,
            "status": self._status.get(job_id, "pending"),
            "progress": self._progress.get(job_id, 0),
        }

    async def cancel_job(self, job_id: str) -> bool:
        self._status[job_id] = "cancelled"
        self._progress.pop(job_id, None)
        return True

    async def job_events(self, request, job_id: str):
        """Yield one progress + one terminal event, then stop."""
        from sse_starlette.event import ServerSentEvent
        import json

        info = self.get_status(job_id)
        # Yield a progress event
        yield ServerSentEvent(
            data=json.dumps({"job_id": job_id, "status": "processing", "progress": 50}),
            event="progress",
        )
        # Yield a terminal status event
        yield ServerSentEvent(
            data=json.dumps(info),
            event="status",
        )


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def event_loop():
    """Create a single event loop for the entire test session."""
    loop = asyncio.new_event_loop()
    yield loop
    loop.close()


@pytest.fixture(autouse=True)
def ensure_current_event_loop():
    """Keep pytest-asyncio runnable after tests that temporarily swap loops."""

    created_loop = None
    try:
        loop = asyncio.get_event_loop()
        if loop.is_closed():
            raise RuntimeError
    except RuntimeError:
        created_loop = asyncio.new_event_loop()
        asyncio.set_event_loop(created_loop)
    yield
    if created_loop is not None and not created_loop.is_closed():
        created_loop.close()
        asyncio.set_event_loop(None)


@pytest_asyncio.fixture(autouse=True)
async def setup_db():
    """Create tables before each test and drop them after."""
    async with test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    yield
    async with test_engine.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)


@pytest_asyncio.fixture
async def client() -> AsyncGenerator[AsyncClient, None]:
    """Provide an httpx AsyncClient wired to the FastAPI app with overrides."""
    from app.main import app, _app_state
    from app.services.conversion_service import ConversionService

    fake_service = FakeMarkerService()
    fake_conversion = ConversionService(fake_service)
    fake_tm = FakeTaskManager()
    fake_tm.set_marker_service(fake_service)

    original_ms = _app_state.marker_service
    original_cs = _app_state.conversion_service
    original_tm = _app_state.task_manager

    _app_state.marker_service = fake_service  # type: ignore[assignment]
    _app_state.conversion_service = fake_conversion  # type: ignore[assignment]
    _app_state.task_manager = fake_tm  # type: ignore[assignment]

    app.dependency_overrides[get_db] = _override_get_db

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://testserver") as ac:
        yield ac

    # Restore
    _app_state.marker_service = original_ms  # type: ignore[assignment]
    _app_state.conversion_service = original_cs  # type: ignore[assignment]
    _app_state.task_manager = original_tm  # type: ignore[assignment]
    app.dependency_overrides.clear()


@pytest_asyncio.fixture
async def db_session() -> AsyncGenerator[AsyncSession, None]:
    """Provide a raw async DB session for direct DB assertions."""
    async with test_session_factory() as session:
        yield session
