"""Context Runtime: bounded typed queries and EvidencePackets (PR77/PR78).

Server-side query core standing on the PR76 publication substrate:
a typed, finite request contract (never agent-authored SQL/FTS5
syntax), execution pinned to exactly one PublicationSet per query,
authorization derived from trusted committed policy state before any
candidate can compete for delivery, structural whole-unit budgets, and
deterministic invalidation-aware EvidencePacket identity.

Transport-agnostic by design: ``execute_query`` is the internal
application-service callable a future agent/tool transport wraps.
No externally reachable retrieval endpoint is exposed at this layer on
purpose — publishing one requires the PR79 transport work to carry the
authorization contract, not just the query contract.
"""

from app.context_runtime.authorization import (
    ASSURANCE_HIGH,
    ASSURANCE_STANDARD,
    AUTHORIZATION_PROFILE_LOCAL,
    EffectiveAuthorization,
    resolve_effective_authorization,
)
from app.context_runtime.continuation import (
    CONTINUATION_SCHEMA_VERSION,
    CONTINUATION_OUTCOME_STATUSES,
    CONTINUATION_TERMINAL_STATUSES,
    CURSOR_REPLAY_CONSUMED,
    CURSOR_REPLAY_FRESH,
    CURSOR_REPLAY_ROTATED,
    CURSOR_STATUS_ACTIVE,
    CURSOR_STATUS_EXHAUSTED,
    CURSOR_STATUS_EXPIRED,
    CURSOR_STATUS_REVOKED,
    ContinuationContractError,
    ContinuationOutcome,
    ContinuationResult,
    CursorReplayState,
    CursorState,
    OUTCOME_COMPLETE,
    OUTCOME_EXECUTION_FAILURE,
    OUTCOME_INVALIDATED,
    OUTCOME_LOOP_LIMIT,
    OUTCOME_PARTIAL,
    OUTCOME_POLICY_FAIL_CLOSED,
    OUTCOME_STALE,
    QueryOutcome,
    canonical_cursor_state_json,
    parse_continuation_outcome,
    parse_cursor_state_json,
    validate_cursor_state_expiry,
)
from app.context_runtime.contract import (
    DEFAULT_QUERY_BUDGET,
    FUTURE_OPERATIONS,
    MAX_LEXICAL_LIMIT,
    MAX_LEXICAL_TEXT_CHARS,
    MAX_OPERATIONS_HARD,
    QUERY_SCHEMA_VERSION,
    SUPPORTED_OPERATIONS,
    LexicalSearchOp,
    QueryAssurance,
    QueryBudget,
    QueryRequest,
    QuerySecurityContext,
    OutputDirective,
    RecordGetOp,
    compile_lexical_match,
    normalized_query,
    parse_query_request,
    validate_request_budget,
)
from app.context_runtime.cursor import (
    CURSOR_HANDLE_BYTES,
    CURSOR_NONCE_BYTES,
    CURSOR_SIGNATURE_BYTES,
    CURSOR_TOKEN_MAX_BYTES,
    CURSOR_TOKEN_VERSION,
    CursorCodec,
    CursorCodecError,
    CursorEnvelope,
    CursorExpiredError,
    CursorIntegrityError,
    CursorKeyError,
    CursorKeyring,
    CursorMalformedError,
    CursorVersionError,
    new_cursor_handle,
    new_cursor_nonce,
    validate_cursor_expiry,
)
from app.context_runtime.errors import (
    QueryAuthorizationError,
    QueryBudgetError,
    QueryContractError,
    QueryError,
    UnsupportedOperatorError,
)
from app.context_runtime.executor import execute_query
from app.context_runtime.packets import (
    EVIDENCE_PACKET_SCHEMA_VERSION,
    BudgetReport,
    CandidateUnit,
    EvidenceLocator,
    EvidencePacket,
    EvidenceUnit,
    OmittedEvidence,
    assemble_packet,
    packet_identity_dimensions,
    to_json,
)

__all__ = [
    "ASSURANCE_HIGH",
    "ASSURANCE_STANDARD",
    "AUTHORIZATION_PROFILE_LOCAL",
    "CONTINUATION_SCHEMA_VERSION",
    "CONTINUATION_OUTCOME_STATUSES",
    "CONTINUATION_TERMINAL_STATUSES",
    "CURSOR_HANDLE_BYTES",
    "CURSOR_NONCE_BYTES",
    "CURSOR_REPLAY_CONSUMED",
    "CURSOR_REPLAY_FRESH",
    "CURSOR_REPLAY_ROTATED",
    "CURSOR_SIGNATURE_BYTES",
    "CURSOR_STATUS_ACTIVE",
    "CURSOR_STATUS_EXHAUSTED",
    "CURSOR_STATUS_EXPIRED",
    "CURSOR_STATUS_REVOKED",
    "CURSOR_TOKEN_MAX_BYTES",
    "CURSOR_TOKEN_VERSION",
    "DEFAULT_QUERY_BUDGET",
    "EVIDENCE_PACKET_SCHEMA_VERSION",
    "FUTURE_OPERATIONS",
    "MAX_LEXICAL_LIMIT",
    "MAX_LEXICAL_TEXT_CHARS",
    "MAX_OPERATIONS_HARD",
    "QUERY_SCHEMA_VERSION",
    "SUPPORTED_OPERATIONS",
    "BudgetReport",
    "CandidateUnit",
    "ContinuationContractError",
    "ContinuationOutcome",
    "ContinuationResult",
    "CursorCodec",
    "CursorCodecError",
    "CursorEnvelope",
    "CursorExpiredError",
    "CursorIntegrityError",
    "CursorKeyError",
    "CursorKeyring",
    "CursorMalformedError",
    "CursorReplayState",
    "CursorState",
    "CursorVersionError",
    "EffectiveAuthorization",
    "EvidenceLocator",
    "EvidencePacket",
    "EvidenceUnit",
    "LexicalSearchOp",
    "OmittedEvidence",
    "OutputDirective",
    "OUTCOME_COMPLETE",
    "OUTCOME_EXECUTION_FAILURE",
    "OUTCOME_INVALIDATED",
    "OUTCOME_LOOP_LIMIT",
    "OUTCOME_PARTIAL",
    "OUTCOME_POLICY_FAIL_CLOSED",
    "OUTCOME_STALE",
    "QueryAssurance",
    "QueryAuthorizationError",
    "QueryBudget",
    "QueryBudgetError",
    "QueryContractError",
    "QueryError",
    "QueryRequest",
    "QuerySecurityContext",
    "RecordGetOp",
    "UnsupportedOperatorError",
    "assemble_packet",
    "compile_lexical_match",
    "execute_query",
    "normalized_query",
    "packet_identity_dimensions",
    "parse_query_request",
    "parse_continuation_outcome",
    "parse_cursor_state_json",
    "resolve_effective_authorization",
    "to_json",
    "QueryOutcome",
    "canonical_cursor_state_json",
    "new_cursor_handle",
    "new_cursor_nonce",
    "validate_cursor_expiry",
    "validate_cursor_state_expiry",
    "validate_request_budget",
]
