"""Verification-risk contracts, policy, and commit gate (PR75)."""

from . import policy as _policy
from .gate import check_batch_verification_risk
from .policy import (
    AUTHORITY_CLASSES,
    AUTHORITY_DETERMINISTIC,
    AUTHORITY_EMPIRICALLY_VALIDATED_MODEL,
    AUTHORITY_HUMAN_REVIEWED,
    AUTHORITY_SOURCE_NATIVE,
    DEPENDENCY_CORRELATED,
    DEPENDENCY_INDEPENDENT,
    DEPENDENCY_UNKNOWN,
    DISCLOSURE_COMPLETE,
    DISCLOSURE_PARTIAL,
    DISCLOSURE_UNKNOWN,
    EVIDENCE_DETERMINISTIC,
    EVIDENCE_HUMAN_REVIEWED,
    EVIDENCE_MIXED,
    EVIDENCE_MODEL,
    EVIDENCE_SOURCE_NATIVE,
    HIGH_RISK_SOURCE_NATIVE_MIN_SAMPLES,
    HIGH_RISK_SOURCE_NATIVE_POLICY_ID,
    HIGH_RISK_SOURCE_NATIVE_POLICY_REVISION,
    HIGH_RISK_SOURCE_NATIVE_RISK_BOUND,
    HIGH_RISK_SOURCE_NATIVE_WORKFLOW,
    OUTCOME_ABSTAINED,
    OUTCOME_ACCEPTED_WITH_WARNING,
    OUTCOME_UNAVAILABLE,
    OUTCOME_UNCERTAIN,
    OUTCOME_VERIFIED,
    REASON_CLAIM_AUTHORITY,
    REASON_EXPIRED,
    REASON_INSUFFICIENT,
    REASON_MODEL_ONLY_HIGH_RISK,
    REASON_RISK_BOUND,
    REASON_SHIFT,
    REASON_SUFFICIENT,
    REASON_UNKNOWN_OR_CORRELATED,
    SHIFT_MATCHED,
    SHIFT_SHIFTED,
    SHIFT_UNKNOWN,
    VerificationRiskDecision,
    VerificationRiskPolicy,
    classify_dependency_status,
    evaluate_verification_risk,
    evaluate_verification_risk_policy,
)
from .records import DependencyDisclosureRecord, VerificationRiskEvidenceRecord

# Compatibility aliases retained for direct imports from the former module.
VERIFICATION_RISK_SCHEMA_VERSION = _policy.VERIFICATION_RISK_SCHEMA_VERSION
RECORD_TYPE_DEPENDENCY_DISCLOSURE = _policy.RECORD_TYPE_DEPENDENCY_DISCLOSURE
RECORD_TYPE_VERIFICATION_RISK_EVIDENCE = _policy.RECORD_TYPE_VERIFICATION_RISK_EVIDENCE
DISCLOSURE_QUALITIES = _policy.DISCLOSURE_QUALITIES
DEPENDENCY_STATUSES = _policy.DEPENDENCY_STATUSES
SHIFT_STATES = _policy.SHIFT_STATES
EVIDENCE_KINDS = _policy.EVIDENCE_KINDS
HIGH_RISK_NON_MODEL_AUTHORITY_CLASSES = _policy.HIGH_RISK_NON_MODEL_AUTHORITY_CLASSES
REASON_SCOPE = _policy.REASON_SCOPE

__all__ = [
    "AUTHORITY_CLASSES", "AUTHORITY_DETERMINISTIC",
    "AUTHORITY_EMPIRICALLY_VALIDATED_MODEL", "AUTHORITY_HUMAN_REVIEWED",
    "AUTHORITY_SOURCE_NATIVE", "DEPENDENCY_CORRELATED",
    "DEPENDENCY_INDEPENDENT", "DEPENDENCY_UNKNOWN", "DISCLOSURE_COMPLETE",
    "DISCLOSURE_PARTIAL", "DISCLOSURE_UNKNOWN", "DependencyDisclosureRecord",
    "VerificationRiskDecision", "VerificationRiskEvidenceRecord",
    "VerificationRiskPolicy", "HIGH_RISK_SOURCE_NATIVE_MIN_SAMPLES",
    "HIGH_RISK_SOURCE_NATIVE_POLICY_ID",
    "HIGH_RISK_SOURCE_NATIVE_POLICY_REVISION",
    "HIGH_RISK_SOURCE_NATIVE_RISK_BOUND", "HIGH_RISK_SOURCE_NATIVE_WORKFLOW",
    "EVIDENCE_DETERMINISTIC", "EVIDENCE_HUMAN_REVIEWED", "EVIDENCE_MIXED",
    "EVIDENCE_MODEL", "EVIDENCE_SOURCE_NATIVE", "OUTCOME_ABSTAINED",
    "OUTCOME_ACCEPTED_WITH_WARNING", "OUTCOME_UNAVAILABLE",
    "OUTCOME_UNCERTAIN", "OUTCOME_VERIFIED", "REASON_CLAIM_AUTHORITY",
    "REASON_EXPIRED", "REASON_INSUFFICIENT", "REASON_MODEL_ONLY_HIGH_RISK",
    "REASON_RISK_BOUND", "REASON_SHIFT", "REASON_UNKNOWN_OR_CORRELATED",
    "REASON_SUFFICIENT", "SHIFT_MATCHED", "SHIFT_SHIFTED", "SHIFT_UNKNOWN",
    "check_batch_verification_risk", "classify_dependency_status",
    "evaluate_verification_risk", "evaluate_verification_risk_policy",
]
